config/routes.rb
Rails.application.routes.draw do

  get 'comics_on_react/index'
  post 'comics_on_react/tuneFigure'
  post 'comics_on_react/tuneSpeech'
  post 'comics_on_react/tuneImage'

  post 'comics_on_react/updateImage'

  # post 'comics_on_react/create'

  post 'comics_on_react/destroyFigure'
  post 'comics_on_react/destroySpeech'
  post 'comics_on_react/destroyImage'

  post 'comics_on_react/saveLayersOrder'

  resources :fonts
  resources :comics do
    resources :frames
    resources :speeches
    resources :bubbles
    resources :figures
    resources :images
  end

  root 'comics#index'
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/comic.rb
class Comic < ApplicationRecord
  has_many :bubbles
  has_many :frames
  has_many :images
  has_many :speeches
  has_many :figures

  validates :name, presence: true
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  before_action :set_comic, only: [:show, :edit, :update, :destroy]

  # GET /comics
  # GET /comics.json
  def index
    @comics = Comic.all
  end

  # GET /comics/1
  # GET /comics/1.json
  def show
    @comics = Comic.find(params[:id])
  end

  # GET /comics/new
  def new
    @comic = Comic.new
  end

  # GET /comics/1/edit
  def edit
  end

  # POST /comics
  # POST /comics.json
  def create
    @comic = Comic.new(comic_params)

    respond_to do |format|
      if @comic.save
        format.html { redirect_to @comic, notice: 'Comic was successfully created.' }
        format.json { render :show, status: :created, location: @comic }
      else
        format.html { render :new }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comics/1
  # PATCH/PUT /comics/1.json
  def update
    respond_to do |format|
      if @comic.update(comic_params)
        format.html { redirect_to @comic, notice: 'Comic was successfully updated.' }
        format.json { render :show, status: :ok, location: @comic }
      else
        format.html { render :edit }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comics/1
  # DELETE /comics/1.json
  def destroy
    @comic.destroy
    respond_to do |format|
      format.html { redirect_to comics_url, notice: 'Comic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def createWithoutForm
    name = 'Oleg'
    c = Comic.new(name: name)
    c.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comic
      @comic = Comic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comic_params
      params.require(:comic).permit(:name)
    end
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/comics/_comicPreview.html.erb
<div class="comicPreview">
  <a class="comicPreviewContainer" href="<%= url_for comic_path(comic) %>">
    <div class="comicPreviewImage"></div>
    <div class="comicPrewiewName"><%= comic.name %></div>
  </a>
  <%= link_to 'Destroy', comic, method: :delete, data: { confirm: 'Are you sure?' }, class: "comicPreviewDestroy"%>
  <!-- <a href="<%=  %>" class="comicPreviewDestroy"><%= image_tag("delete.svg", size: "20x20") %></a> -->
</div>

app/views/comics/_form.html.erb
<%= form_with(model: comic, local: true) do |form| %>
  <div class="Sidebar">
    <div class="comicsHeader">
      <div class="comicsHeaderBacklink"><%= link_to '< To comics', comics_path %></div>

      <div class="field">
        <%= form.label :name %>
        <%= form.text_area :name %>
      </div>

    </div>
    <div class="actions">
      <%= form.submit %>
    </div>

    <% if comic.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comic.errors.count, "error") %> prohibited this comic from being saved:</h2>

        <ul>
        <% comic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>



<% end %>

app/views/comics/edit.html.erb
<h1>Editing Comic</h1>

<%= render 'form', comic: @comic %>

<%= link_to 'Show', @comic %> |
<%= link_to 'Back', comics_path %>

app/views/comics/index.html.erb
<div class="comicPreviews">
  <div class="logo"></div>
  <div class="comicPreviewsHeaders">
    <h1>Simple and fast way to create animated web-comics</h1>
    <h2>Version 0.0.1. You can create and even edit objects</h2>
  </div>

  <a class="comicPreviewNewComic"href="<%= new_comic_path %>">
    <%= image_tag("plus.svg") %>
    Create comic
  </a>
<%#= @comics.any? %>
  <%# if @comics.any? %>
    <% @comics.each do |comic| %>
      <%= render "comics/comicPreview", comic: comic %>
    <% end %>
  <%# end %>
</div>
<div class="authors">
  <h2>Настя, Даша, Настюша, Саша. HSE DC'2020</h2>
</div>

app/views/comics/new.html.erb
<h1>New Comic</h1>

<%= render 'form', comic: @comic %>

<%= link_to 'Back', comics_path %>

app/views/comics/show.html.erb
<%# @fonts = Font.all %>
<%# content_for :head do %>
  <%# @fonts.each do |f| %>
    <%#= '<plink href="' + f.link + '" rel="stylesheet">'%>
  <%# end %>
<%# end %>






<section class="Sidebar">
  <div class="comicsHeader">
    <div class="comicsHeaderBacklink"><%= link_to '< To comics', comics_path %></div>
    <div class="comicsHeaderName"><%= link_to @comic.name, edit_comic_path(@comic) %></div>
  </div>

  <% @comic.figures.all.each do |figure|%>
    <%= render "figures/figureListItem", figure: figure %>
  <% end  %>

  <% @comic.images.all.each do |image|%>
    <%= render "images/imageListItem",image: image %>
  <% end  %>

  <% @comic.speeches.all.each do |speech|%>
    <%= render "speeches/speechListItem", speech: speech %>
  <% end  %>

  <%#
    objects = []

    def push_things_to_array(things, array)
      things.all.each do |thing|
        if thing.z_index.nil?
          thing.z_index = 0
        end
        array.push([thing.z_index, (things.model_name.to_s + ' ' + thing.id.to_s)])
      end
      return array
    end

    objects = push_things_to_array(@comic.figures, objects)
    objects = push_things_to_array(@comic.speeches, objects)
    objects = push_things_to_array(@comic.images, objects)

    objects = objects.sort_by {|elem| elem[0]}
    layers_amount = objects.size
  %>

  <!-- <p><%#= objects %> | All: <%#= layers_amount %></p> -->
</section>

<section class="ComicsArtbord">
  <div class="newComicItem">
    <div class="newComicItemButton"></div>
    <div class="newComicItemMenu">
      <a class="newComicItemMenuItem" href="<%= url_for new_comic_figure_path(@comic) %>"><div class="icon newComicFigureIcon"></div>Figure</a>
      <!-- <a class="newComicItemMenuItem" href="<%#= url_for new_comic_bubble_path(@comic) %>"><div class="icon newComicBubbleIcon"></div>Bubble</a> -->
      <a class="newComicItemMenuItem" href="<%= url_for new_comic_image_path(@comic) %>"><div class="icon newComicPictureIcon"></div>Image</a>
      <a class="newComicItemMenuItem" href="<%= url_for new_comic_speech_path(@comic) %>"><div class="icon newComicTextIcon"></div>Text</a>
      <a class="newComicItemMenuItem newComicItemMenuItemLine" href="<%= url_for new_font_path %>"><div class="icon"></div>Add font</a>
    </div>
  </div>

  <% @comic.figures.each do |f| %>
    <% if f.frame_id.nil? %>
      <%= render f %>
    <% end %>
  <% end %>

  <%= render @comic.frames %>

  <% @comic.images.each do |i| %>
    <% if i.frame_id.nil? %>
      <%= render i %>
    <% end %>
  <% end %>

  <% @comic.speeches.each do |s| %>
    <% if s.frame_id.nil? %>
      <%= render s %>
    <% end %>
  <% end %>

  <%#= render @comic.bubbles %>
  <%#= render @comic.figures %>
  <%#= render @comic.bubbles %>
  <%#= render @comic.speeches %>
  <%#= render @comic.frames %>
  <%#= render @comic.images %>
</section>