config/routes.rb
Rails.application.routes.draw do

  get 'comics_on_react/index'
  post 'comics_on_react/tuneFigure'
  post 'comics_on_react/tuneSpeech'
  post 'comics_on_react/tuneImage'

  post 'comics_on_react/updateImage'

  # post 'comics_on_react/create'

  post 'comics_on_react/destroyFigure'
  post 'comics_on_react/destroySpeech'
  post 'comics_on_react/destroyImage'

  post 'comics_on_react/saveLayersOrder'

  resources :fonts
  resources :comics do
    resources :frames
    resources :speeches
    resources :bubbles
    resources :figures
    resources :images
  end

  root 'comics#index'
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/speech.rb
class Speech < ApplicationRecord
  belongs_to :comic
  belongs_to :frame, optional: true
  belongs_to :font, optional: true

  validates :comic_id, :x, :y, :width, :height, presence: true
end

app/controllers/speeches_controller.rb
class SpeechesController < ApplicationController
  before_action :set_speech, only: [:show, :edit, :update, :destroy]

  # GET /speeches
  # GET /speeches.json
  def index
    @speeches = Speech.all
  end

  # GET /speeches/1
  # GET /speeches/1.json
  def show
  end

  # GET /speeches/new
  def new
    @comic = Comic.find(params[:comic_id])
    @speech = @comic.speeches.new
  end

  # GET /speeches/1/edit
  def edit
    @comic = @speech.comic
    @@old_z_index = @speech.z_index
  end

  # POST /speeches
  # POST /speeches.json
  def create
    @comic = Comic.find(params[:comic_id])
    @speech = Speech.new(speech_params)
    @speech.comic_id = params[:comic_id]
    @speech.z_index = objects_quantity(@speech.comic) + 1

    respond_to do |format|
      if @speech.save
        format.json { render json: {speech_id: @speech.id},  status: :ok }
        # format.html { redirect_to @comic, notice: 'Speech was successfully created.' }
        # format.json { render :show, status: :created, location: @speech }
      else
        # format.html { render :new }
        # format.json { render json: @speech.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /speeches/1
  # PATCH/PUT /speeches/1.json
  def update
    @comic = @speech.comic

    respond_to do |format|
      if @speech.update(speech_params)
        format.html { redirect_to @comic, notice: 'Speech was successfully updated.' }
        format.json { render :show, status: :ok, location: @speech }
      else
        format.html { render :edit }
        format.json { render json: @speech.errors, status: :unprocessable_entity }
      end
    end

    @new_z_index = @speech.z_index

    change_z_indexes(@comic.figures, @speech, @new_z_index, @@old_z_index)
    change_z_indexes(@comic.speeches, @speech, @new_z_index, @@old_z_index)
    change_z_indexes(@comic.images, @speech, @new_z_index, @@old_z_index)

  end

  # DELETE /speeches/1
  # DELETE /speeches/1.json
  def destroy
    @speech.destroy
    respond_to do |format|
      format.html { redirect_to @speech.comic, notice: 'Speech was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speech
      @speech = Speech.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def speech_params
      params.require(:speech).permit(:text, :x, :y, :width, :height, :font_size, :line_height, :color, :background_color, :comic_id, :frame_id, :font_id, :z_index)
    end
end

app/helpers/speeches_helper.rb
module SpeechesHelper
end

app/views/speeches/_form.html.erb
<%= form_with(model: [@comic, @speech], local: true) do |form| %>
  <% if @speech.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(@speech.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
      <% @speech.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="Sidebar">
    <div class="comicsHeader">
      <div class="comicsHeaderBacklink"><%= link_to '< To comics', comics_path %></div>
      <div class="comicsHeaderName"><%= link_to @comic.name, edit_comic_path(@comic) %></div>
    </div>

    <div class="formName">
      Text
    </div>

    <div class="field">
      <%= form.label :text %>
      <%= form.text_area :text%>
    </div>

    <div class="fieldTwoInLine">
      <div class="field">
        <%= form.label :x %>
        <%= form.number_field :x%>
      </div>

      <div class="field">
        <%= form.label :y %>
        <%= form.number_field :y%>
      </div>
    </div>

    <div class="fieldTwoInLine">
      <div class="field">
        <%= form.label :width %>
        <%= form.number_field :width%>
      </div>

      <div class="field">
        <%= form.label :height %>
        <%= form.number_field :height%>
      </div>
    </div>

    <div class="field">
      <%= form.label :font_id %>
      <%#= form.text_field :font_id %>
      <%= select("speech", "font_id", Font.all.collect { |a| [a.title, a.id] }, { include_blank: true }) %>
    </div>

    <div class="field">
      <%= form.label :font_size %>
      <%= form.number_field :font_size%>
    </div>
    
    <div class="field">
      <%= form.label :line_height %>
      <%= form.number_field :line_height%>
    </div>

    <div class="field">
      <%= form.label :color %>
      <%= form.text_field :color, :autocomplete => :off %>
    </div>

    <div class="field">
      <%= form.label :background_color %>
      <%= form.text_field :background_color, :autocomplete => :off %>
    </div>

    <div class="field">
      <%= form.label :frame_id %>
      <%#= form.text_field :frame_id %>
      <%= select("speech", "frame_id", @comic.frames.all.collect { |a| [a.frame, a.id] }, { include_blank: true }) %>
    </div>

    <div class="field">
      <%= form.label :layer %>
      <%= form.number_field :z_index, :autocomplete => :off, in: 1..(@comic.figures.count + @comic.speeches.count + @comic.images.count) %>
      max value: <%= @comic.figures.count + @comic.speeches.count + @comic.images.count %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
  <section class="ComicsArtbord">
    <%= render @comic.figures.all %>
    <%= render @comic.bubbles.all %>
    <%= render @comic.speeches.all %>
    <%= render @comic.frames.all %>
    <%= render @comic.images.all %>
  </section>
<% end %>

app/views/speeches/_speech.html.erb
<%
  y = speech.y.to_s
  x = speech.x.to_s
  width = speech.width.to_s
  height = speech.height.to_s
  bg_color = speech.background_color
  font_size = speech.font_size
  line_height = speech.line_height.to_s
  color = speech.color
  # font_title = speech.font.title
  z_index = speech.z_index.to_s

  position = "position: absolute;"
  top = "top: #{ y }px;" if y != ""
  left = "left: #{ x }px;" if x != ""
  width = "width: #{ width }px;" if width != ""
  height = "height: #{ height }px;" if height != ""
  background_color = "background-color: #{ bg_color };" if bg_color != ""
  font_size = "font-size: #{ font_size }px;" if font_size != ""
  line_height = "line-height: #{ line_height }px;"
  color = "color: #{ color };" if color != ""
  z_index = "z-index: #{ z_index };" if z_index != ""
  # font_title = "font-family: #{ font_title };" if font_title != ""

  style = [
    position, top, left, width, height, background_color,
    font_size, color, z_index, line_height,
    # font_title
  ].join(" ")
%>

<%= content_tag :div, class: 'speech', style: style do %>
  <%= speech.text %> <br>
  <div class="editButtons">
    <%= link_to "Edit", edit_comic_speech_path(@comic, speech), class: 'editButton' %>
    <%= link_to 'Destroy', comic_speech_path(@comic, speech), method: :delete, data: { confirm: 'Are you sure?' }, class: 'editButton' %>
  </div>
<% end %>

app/views/speeches/_speechListItem.html.erb
<a class="LayerListItem" href="<%= url_for edit_comic_speech_path(@comic, speech) %>">
  <div class="icon newComicTextIcon"></div>
  Text
  <%= speech.id%>
</a>

app/views/speeches/edit.html.erb
<h1>Editing Speech</h1>

<%= render 'form', speech: @speech %>

<%#= link_to 'Show', @speech %> 
<%= link_to 'Back', @speech.comic %>

app/views/speeches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Speeches</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>X</th>
      <th>Y</th>
      <th>Width</th>
      <th>Height</th>
      <th>Font size</th>
      <th>Line height</th>
      <th>Font color</th>
      <th>Background color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @speeches.each do |speech| %>
      <tr>
        <td><%= speech.text %></td>
        <td><%= speech.x %></td>
        <td><%= speech.y %></td>
        <td><%= speech.width %></td>
        <td><%= speech.height %></td>
        <td><%= speech.font_size %></td>
        <td><%= speech.line_height %></td>
        <td><%= speech.color %></td>
        <td><%= speech.background_color %></td>
        <td><%#= link_to 'Show', comic_speech_path(@comic, speech) %></td>
        <td><%#= link_to 'Edit', edit_comic_speech_path(@comic, speech) %></td>
        <td><%#= link_to 'Destroy', comic_speech_path(@comic, speech), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Speech', new_comic_speech_path %>

app/views/speeches/new.html.erb
<h1>New Text</h1>

<%= render 'form', speech: @speech %>

<%= link_to 'Back', @speech.comic %>

app/views/speeches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @speech.text %>
</p>

<p>
  <strong>X:</strong>
  <%= @speech.x %>
</p>

<p>
  <strong>Y:</strong>
  <%= @speech.y %>
</p>

<p>
  <strong>Width:</strong>
  <%= @speech.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @speech.height %>
</p>

<p>
  <strong>Font size:</strong>
  <%= @speech.font_size %>
</p>

<p>
  <strong>Line height:</strong>
  <%= @speech.line_height %>
</p>

<p>
  <strong>Font color:</strong>
  <%= @speech.color %>
</p>

<p>
  <strong>Background color:</strong>
  <%= @speech.background_color %>
</p>

<p>
  <strong>Font:</strong>
  <%= @speech.font.title %>
</p>

<%#= link_to 'Edit', edit_speech_path(@speech) %> |
<%#= link_to 'Back', speeches_path %>