config/routes.rb
Rails.application.routes.draw do

  get 'comics_on_react/index'
  post 'comics_on_react/tuneFigure'
  post 'comics_on_react/tuneSpeech'
  post 'comics_on_react/tuneImage'

  post 'comics_on_react/updateImage'

  # post 'comics_on_react/create'

  post 'comics_on_react/destroyFigure'
  post 'comics_on_react/destroySpeech'
  post 'comics_on_react/destroyImage'

  post 'comics_on_react/saveLayersOrder'

  resources :fonts
  resources :comics do
    resources :frames
    resources :speeches
    resources :bubbles
    resources :figures
    resources :images
  end

  root 'comics#index'
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :comic
  belongs_to :frame, optional: true

  validates :comic_id, :x, :y, :width, :height, presence: true

  # mount_base64_uploader :image, ImageUploader
  mount_uploader :image, ImageUploader
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @comic = Comic.find(params[:comic_id])
    @image = @comic.images.new
  end

  # GET /images/1/edit
  def edit
    @comic = @image.comic
    @@old_z_index = @image.z_index
  end

  # POST /images
  # POST /images.json
  def create
    # @image = Image.new(image_params)
    @comic = Comic.find(params[:comic_id])
    @image = Image.new(image_params)
    @image.comic_id = params[:comic_id]
    @image.z_index = objects_quantity(@image.comic) + 1

    respond_to do |format|
      if @image.save
        format.json { render json: {image_id: @image.id},  status: :ok }
        # @comic = @image.comic
        # format.html { redirect_to @comic, notice: 'Image was successfully created.' }
        # format.json { render :show, status: :created, location: @image }
      else
        # format.html { render :new }
        # format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    @comic = @image.comic

    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @comic, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end

    @new_z_index = @image.z_index

    change_z_indexes(@comic.figures, @image, @new_z_index, @@old_z_index)
    change_z_indexes(@comic.speeches, @image, @new_z_index, @@old_z_index)
    change_z_indexes(@comic.images, @image, @new_z_index, @@old_z_index)

  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to @image.comic, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:image, :x, :y, :width, :height, :comic_id, :frame_id, :z_index)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_with(model: [@comic, @image]) do |form| %>
  <% if @image.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="Sidebar">
    <div class="comicsHeader">
      <div class="comicsHeaderBacklink"><%= link_to '< To comics', comics_path %></div>
      <div class="comicsHeaderName"><%= link_to @comic.name, edit_comic_path(@comic) %></div>
    </div>

    <div class="formName">
      Image
    </div>

    <div class="field">
      <%= form.label :frame_id %>
      <%#= form.text_field :frame_id %>
      <%= select("image", "frame_id", @comic.frames.all.collect { |a| [a.frame, a.id] }, { include_blank: true }) %>
    </div>


    <div class="field fieldNoBg">
      <%= form.label :image, 'Select Image' %>
      <%= form.file_field :image %>
    </div>

    <div class="field">
      <%= form.label :x %>
      <%= form.number_field :x%>
    </div>

    <div class="field">
      <%= form.label :y %>
      <%= form.number_field :y%>
    </div>

    <div class="field">
      <%= form.label :width %>
      <%= form.number_field :width%>
    </div>

    <div class="field">
      <%= form.label :height %>
      <%= form.number_field :height%>
    </div>

    <div class="field">
      <%= form.label :layer %>
      <%= form.number_field :z_index, :autocomplete => :off, in: 1..(@comic.figures.count + @comic.speeches.count + @comic.images.count) %>
      max value: <%= @comic.figures.count + @comic.speeches.count + @comic.images.count %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
  <section class="ComicsArtbord">
    <%= render @comic.figures.all %>
    <%= render @comic.bubbles.all %>
    <%= render @comic.speeches.all %>
    <%= render @comic.frames.all %>
    <%= render @comic.images.all %>
  </section>
<% end %>

app/views/images/_image.html.erb
<%
  y = image.y.to_s
  x = image.x.to_s
  width = image.width.to_s
  height = image.height.to_s
  bg_image = image.image.url
  z_index = image.z_index.to_s

  position = "position: absolute;"
  top = "top: #{ y }px;" if y != ""
  left = "left: #{ x }px;" if x != ""
  width = "width: #{ width }px;" if width != ""
  height = "height: #{ height }px;" if height != ""
  bg_image = "background-image: url(#{ bg_image });"
  bg_size = "background-size: cover;"
  z_index = "z-index: #{ z_index };" if z_index != ""


  style = [
    position, top, left, width, height, bg_image, bg_size, z_index
  ].join(" ")
%>

<%= content_tag :div, class: 'image', style: style do %>
  <div class="editButtons">
    <%= link_to "Edit", edit_comic_image_path(@comic, image), class: 'editButton' %>
    <%= link_to 'Destroy', comic_image_path(@comic, image), method: :delete, data: { confirm: 'Are you sure?' }, class: 'editButton' %>
  </div>
<% end %>

app/views/images/_imageListItem.html.erb
<a class="LayerListItem" href="<%= url_for edit_comic_image_path(@comic, image) %>">
  <div class="icon newComicPictureIcon"></div>
  <%= image.model_name.to_s%>
  <%= image.id%>
</a>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%#= link_to 'Show', @image %> 
<%= link_to 'Back', @image.comic %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>X</th>
      <th>Y</th>
      <th>Width</th>
      <th>Height</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.image %></td>
        <td><%= image.frame_id %></td>
        <td><%= image.x %></td>
        <td><%= image.y %></td>
        <td><%= image.width %></td>
        <td><%= image.height %></td>
        <td><%#= link_to 'Show', comic_image_path(@comic, image) %></td>
        <td><%#= link_to 'Edit', edit_comic_image_path(@comic, image) %></td>
        <td><%#= link_to 'Destroy', comic_image_path(@comic, image), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_comic_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', @image.comic %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @image.image %>
</p>

<p>
  <strong>X:</strong>
  <%= @image.x %>
</p>

<p>
  <strong>Y:</strong>
  <%= @image.y %>
</p>

<p>
  <strong>Width:</strong>
  <%= @image.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @image.height %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>