config/routes.rb
Rails.application.routes.draw do

  get 'comics_on_react/index'
  post 'comics_on_react/tuneFigure'
  post 'comics_on_react/tuneSpeech'
  post 'comics_on_react/tuneImage'

  post 'comics_on_react/updateImage'

  # post 'comics_on_react/create'

  post 'comics_on_react/destroyFigure'
  post 'comics_on_react/destroySpeech'
  post 'comics_on_react/destroyImage'

  post 'comics_on_react/saveLayersOrder'

  resources :fonts
  resources :comics do
    resources :frames
    resources :speeches
    resources :bubbles
    resources :figures
    resources :images
  end

  root 'comics#index'
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bubble.rb
class Bubble < ApplicationRecord
  belongs_to :comic
  belongs_to :frames, optional: true
  belongs_to :shape

  validates :comic_id, :x, :y, :shape_id, presence: true
end

app/models/comic.rb
class Comic < ApplicationRecord
  has_many :bubbles
  has_many :frames
  has_many :images
  has_many :speeches
  has_many :figures

  validates :name, presence: true
end

app/models/figure.rb
class Figure < ApplicationRecord
  belongs_to :comic
  belongs_to :frame, optional: true

  validates :comic_id, :x, :y, :width, :height, presence: true
end

app/models/font.rb
class Font < ApplicationRecord
  has_many :speeches
end

app/models/frame.rb
class Frame < ApplicationRecord
  belongs_to :comic
  has_many :figures
  has_many :images
  has_many :speeches

  validates :comic_id, :x, :y, :width, :height, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :comic
  belongs_to :frame, optional: true

  validates :comic_id, :x, :y, :width, :height, presence: true

  # mount_base64_uploader :image, ImageUploader
  mount_uploader :image, ImageUploader
end

app/models/shape.rb
class Shape < ApplicationRecord
   has_many :bubbles
end

app/models/speech.rb
class Speech < ApplicationRecord
  belongs_to :comic
  belongs_to :frame, optional: true
  belongs_to :font, optional: true

  validates :comic_id, :x, :y, :width, :height, presence: true
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  before_action :set_comic, only: [:show, :edit, :update, :destroy]

  # GET /comics
  # GET /comics.json
  def index
    @comics = Comic.all
  end

  # GET /comics/1
  # GET /comics/1.json
  def show
    @comics = Comic.find(params[:id])
  end

  # GET /comics/new
  def new
    @comic = Comic.new
  end

  # GET /comics/1/edit
  def edit
  end

  # POST /comics
  # POST /comics.json
  def create
    @comic = Comic.new(comic_params)

    respond_to do |format|
      if @comic.save
        format.html { redirect_to @comic, notice: 'Comic was successfully created.' }
        format.json { render :show, status: :created, location: @comic }
      else
        format.html { render :new }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comics/1
  # PATCH/PUT /comics/1.json
  def update
    respond_to do |format|
      if @comic.update(comic_params)
        format.html { redirect_to @comic, notice: 'Comic was successfully updated.' }
        format.json { render :show, status: :ok, location: @comic }
      else
        format.html { render :edit }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comics/1
  # DELETE /comics/1.json
  def destroy
    @comic.destroy
    respond_to do |format|
      format.html { redirect_to comics_url, notice: 'Comic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def createWithoutForm
    name = 'Oleg'
    c = Comic.new(name: name)
    c.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comic
      @comic = Comic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comic_params
      params.require(:comic).permit(:name)
    end
end

app/controllers/fonts_controller.rb
class FontsController < ApplicationController
  before_action :set_font, only: [:show, :edit, :update, :destroy]

  # GET /fonts
  # GET /fonts.json
  def index
    @fonts = Font.all
  end

  # GET /fonts/1
  # GET /fonts/1.json
  def show
  end

  # GET /fonts/new
  def new
    @font = Font.new
  end

  # GET /fonts/1/edit
  def edit
  end

  # POST /fonts
  # POST /fonts.json
  def create
    @font = Font.new(font_params)

    respond_to do |format|
      if @font.save
        format.html { redirect_to @font, notice: 'Font was successfully created.' }
        format.json { render :show, status: :created, location: @font }
      else
        format.html { render :new }
        format.json { render json: @font.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fonts/1
  # PATCH/PUT /fonts/1.json
  def update
    respond_to do |format|
      if @font.update(font_params)
        format.html { redirect_to @font, notice: 'Font was successfully updated.' }
        format.json { render :show, status: :ok, location: @font }
      else
        format.html { render :edit }
        format.json { render json: @font.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fonts/1
  # DELETE /fonts/1.json
  def destroy
    @font.destroy
    respond_to do |format|
      format.html { redirect_to fonts_url, notice: 'Font was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_font
      @font = Font.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def font_params
      params.require(:font).permit(:title, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bubbles_helper.rb
module BubblesHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/figures_helper.rb
module FiguresHelper
end

app/helpers/fonts_helper.rb
module FontsHelper
end

app/helpers/frames_helper.rb
module FramesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/shapes_helper.rb
module ShapesHelper
end

app/helpers/speeches_helper.rb
module SpeechesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inkie</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= favicon_link_tag asset_path('favicon.png') %>

    <% @fonts = Font.all %>
    <% @fonts.each do |f| %>
      <link href=' <%= f.link %> ' rel="stylesheet">
    <% end %>

    <%# if content_for? :head %>
      <%#= yield :head %>
    <%# end %>
  </head>

  <body>
    <nav>
      <%#= link_to 'Comics',   comics_url  %>
      <%#= link_to 'Bubbles',  bubbles_url  %>
      <%#= link_to 'Figures',  figures_url  %>
      <%#= link_to 'Frames',   frames_url  %>
      <%#= link_to 'Images',   images_url  %>
      <%#= link_to 'Speeches', speeches_url  %>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/layouts/comics_on_react.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inkie</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'T_ComicsEditor' %>
</head>

<body data-figures="<%= @comic.figures.as_json.to_json %>" data-images="<%= @comic.images.as_json.to_json %>" data-speeches="<%= @comic.speeches.as_json.to_json %>">
  <!-- Здесь будет React -->
</body>
</html>

app/views/texts/_form.html.erb
<%= form_with(model: text, local: true) do |form| %>
  <% if text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(text.errors.count, "error") %> prohibited this text from being saved:</h2>

      <ul>
      <% text.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="field">
    <%= form.label :x %>
    <%= form.number_field :x %>
  </div>

  <div class="field">
    <%= form.label :y %>
    <%= form.number_field :y %>
  </div>

  <div class="field">
    <%= form.label :width %>
    <%= form.number_field :width %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height %>
  </div>

  <div class="field">
    <%= form.label :font_family %>
    <%= form.text_field :font_family %>
    <%#= select("text", "font_family", Text.all.collect {|t| [ t.name, t.family ] }, { include_blank: true }) %>
  </div>

  <div class="field">
    <%= form.label :font_size %>
    <%= form.number_field :font_size %>
  </div>

  <div class="field">
    <%= form.label :font_style %>
    <%= form.text_field :font_style %>
  </div>

  <div class="field">
    <%= form.label :font_color %>
    <%= form.text_field :font_color %>
  </div>

  <div class="field">
    <%= form.label :background_color %>
    <%= form.text_field :background_color %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/texts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @text.text %>
</p>

<p>
  <strong>X:</strong>
  <%= @text.x %>
</p>

<p>
  <strong>Y:</strong>
  <%= @text.y %>
</p>

<p>
  <strong>Width:</strong>
  <%= @text.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @text.height %>
</p>

<p>
  <strong>Font family:</strong>
  <%= @text.font_family %>
</p>

<p>
  <strong>Font size:</strong>
  <%= @text.font_size %>
</p>

<p>
  <strong>Font style:</strong>
  <%= @text.font_style %>
</p>

<p>
  <strong>Font color:</strong>
  <%= @text.font_color %>
</p>

<p>
  <strong>Background color:</strong>
  <%= @text.background_color %>
</p>

<%= link_to 'Edit', edit_text_path(@text) %> |
<%= link_to 'Back', texts_path %>